name: deploy

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: checkout
      uses: actions/checkout@v4
    
    -
      name: Login to Doker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - 
      name: Set up Docker Buildx
      uses: docker/setup.buldx-actions@v3

    -
      name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: ${{ secrets.DCKERHUB_USERNAME }}/nest-demo:latest
      
      
